// GET DATA

export const GET_DATA_START = 'GET_DATA_START';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';

// UPDATE

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAIL = 'UPDATE_FAIL';

// Find Rate

export const FIND_RATE_SELECT = 'FIND_RATE_SELECT';
export const FIND_RATE_RESULT = 'FIND_RATE_RESULT';